version: '3.8'

services:
  web:
    build: .
    command: gunicorn CarSertSite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: fde.settings

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/programs/CarSertSite/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
      - /var/www/certbot:/var/www/certbot
      - /root/programs/CarSertSite/static:/usr/share/nginx/html/static
    depends_on:
      - web
    command: /bin/sh -c "chmod -R 755 /usr/share/nginx/html/static && nginx -g 'daemon off;'"
