# Generated by Django 4.2.16 on 2024-10-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(default='', null=True, verbose_name='Краткое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('wheelbase', 'Колесная база'), ('engine', 'Двигатель'), ('transmission', 'Трансмиссия'), ('brakes', 'Тормоза'), ('suspension', 'Подвеска'), ('windows', 'Стекла'), ('fuel_system', 'Топливная система'), ('lighting', 'Световая система'), ('exhaust', 'Выхлопная система'), ('safety', 'Система безопасности')], default='', max_length=50, null=True, verbose_name='Категория')),
                ('title', models.CharField(default='', max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(default='', null=True, verbose_name='Описание')),
                ('characteristics', models.TextField(default='', null=True, verbose_name='Характеристики')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='main.project')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_sert', models.TextField(blank=True, default='', null=True, verbose_name='Выжимка')),
                ('is_passed', models.BooleanField(default=False, verbose_name='Зачитывается')),
                ('comment', models.TextField(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='main.requirement')),
            ],
        ),
    ]
